# Generated by Django 5.1.2 on 2025-04-18 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_aliasproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoNoReconocido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_detectado', models.CharField(max_length=200)),
                ('fecha_detectado', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
    ]
