# Generated by Django 5.1.2 on 2025-05-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_productonoreconocido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productonoreconocido',
            name='origen',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default='compra', max_length=10),
        ),
    ]
