# Generated by Django 5.1.2 on 2025-09-20 04:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_productonoreconocido_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliasproducto',
            name='alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='aliasproducto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('alias'), name='uniq_alias_ci'),
        ),
    ]
