# Generated by Django 5.1.2 on 2025-10-08 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_aliasproducto_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productonoreconocido',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productonoreconocido',
            name='movimiento_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productonoreconocido',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productonoreconocido',
            name='producto',
            field=models.ForeignKey(blank=True, help_text='Producto real al que corresponde este hallazgo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
    ]
