# Generated by Django 5.1.2 on 2025-10-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_productonoreconocido_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productonoreconocido',
            name='raw_conceptos',
            field=models.JSONField(blank=True, help_text='Snapshot de líneas detectadas por el extractor', null=True),
        ),
    ]
