# Generated by Django 5.1.2 on 2025-11-09 22:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_productonoreconocido_raw_conceptos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_transporte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
