# Generated by Django 5.1.2 on 2025-12-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_producto_costo_transporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-activo', 'nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='False si fue fusionado o descontinuado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_fusion',
            field=models.DateTimeField(blank=True, help_text='Cuándo fue fusionado este producto', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fusionado_en',
            field=models.ForeignKey(blank=True, help_text='Producto principal si este fue fusionado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_fusionados', to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='LogFusionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_secundario_id', models.IntegerField(help_text='ID del producto fusionado')),
                ('producto_secundario_nombre', models.CharField(help_text='Nombre del producto fusionado al momento de la fusión', max_length=200)),
                ('stock_transferido', models.IntegerField(default=0, help_text='Cuánto stock se transfirió')),
                ('fecha_fusion', models.DateTimeField(auto_now_add=True, help_text='Cuándo se realizó la fusión')),
                ('razon', models.TextField(blank=True, help_text='Motivo de la fusión')),
                ('revertida', models.BooleanField(default=False, help_text='True si la fusión fue revertida')),
                ('fecha_reversion', models.DateTimeField(blank=True, help_text='Cuándo se revirtió la fusión', null=True)),
                ('producto_principal', models.ForeignKey(help_text='Producto que absorbió al secundario', on_delete=django.db.models.deletion.CASCADE, related_name='fusiones_recibidas', to='inventario.producto')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la fusión', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Fusión de Productos',
                'verbose_name_plural': 'Logs de Fusión de Productos',
                'ordering': ['-fecha_fusion'],
            },
        ),
    ]
