# Generated by Django 5.1.2 on 2025-12-16 22:45

import django.db.models.deletion
from django.db import migrations, models


def poblar_producto_principal_nombre(apps, schema_editor):
    """Poblar el campo producto_principal_nombre con nombres de productos existentes."""
    LogFusionProductos = apps.get_model('inventario', 'LogFusionProductos')
    for log in LogFusionProductos.objects.all():
        if log.producto_principal:
            log.producto_principal_nombre = log.producto_principal.nombre
            log.save(update_fields=['producto_principal_nombre'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_agregar_sistema_fusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfusionproductos',
            name='producto_principal_nombre',
            field=models.CharField(default='', help_text='Nombre del producto principal al momento de la fusión', max_length=200),
        ),
        migrations.AlterField(
            model_name='logfusionproductos',
            name='producto_principal',
            field=models.ForeignKey(help_text='Producto que absorbió al secundario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_recibidas', to='inventario.producto'),
        ),
        migrations.RunPython(poblar_producto_principal_nombre, migrations.RunPython.noop),
    ]
