# Generated by Django 5.1.2 on 2025-02-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detallefactura_pagofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
