# Generated by Django 5.1.2 on 2025-02-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_detallefactura_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
