# Generated by Django 5.1.2 on 2025-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detallefactura_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10),
            preserve_default=False,
        ),
    ]
