# Generated by Django 5.1.2 on 2025-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_factura_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('revisado_ok', 'Revisado OK'), ('revisado_con_cambios', 'Revisado con cambios')], default='pendiente', help_text='Estado de revisión de la factura', max_length=30),
        ),
        migrations.AddField(
            model_name='factura',
            name='requiere_revision_manual',
            field=models.BooleanField(default=False, help_text='Indica si la factura requiere revisión manual por productos no reconocidos'),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid_factura',
            field=models.CharField(blank=True, help_text='UUID del CFDI para vincular con PNR', max_length=100, null=True),
        ),
    ]
