# Generated by Django 5.1.2 on 2025-12-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_modificar_log_fusion_productos'),
        ('ventas', '0008_agregar_campos_revision'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detallefactura',
            constraint=models.UniqueConstraint(fields=('factura', 'producto'), name='unique_factura_producto'),
        ),
    ]
