# Generated by Django 5.1.2 on 2025-12-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_agregar_unique_constraint_detalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagofactura',
            options={'ordering': ['-fecha_pago', '-creado_en'], 'verbose_name': 'Pago de Factura', 'verbose_name_plural': 'Pagos de Facturas'},
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de crédito/débito'), ('deposito', 'Depósito bancario'), ('otro', 'Otro')], default='efectivo', help_text='Método de pago utilizado', max_length=20),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True),
        ),
        migrations.AddField(
            model_name='pagofactura',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de transferencia, cheque, etc.', max_length=100, null=True),
        ),
    ]
