# Generated by Django 5.1.2 on 2025-12-23 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_pagofactura_options_pagofactura_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de descuento aplicado', max_digits=12),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal antes de descuentos', max_digits=12),
        ),
    ]
