# Generated by Django 5.1.2 on 2025-12-31 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_factura_descuento_factura_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_complemento', models.CharField(help_text='Folio del complemento (ej: 1047)', max_length=20, unique=True)),
                ('uuid_complemento', models.CharField(help_text='UUID del CFDI del complemento', max_length=100, unique=True)),
                ('fecha_emision', models.DateField(help_text='Fecha de emisión del complemento CFDI')),
                ('fecha_pago', models.DateField(help_text='Fecha real en que se recibió el pago')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Monto total del pago', max_digits=12)),
                ('forma_pago_sat', models.CharField(choices=[('01', '01 - Efectivo'), ('02', '02 - Cheque nominativo'), ('03', '03 - Transferencia electrónica de fondos'), ('04', '04 - Tarjeta de crédito'), ('05', '05 - Monedero electrónico'), ('28', '28 - Tarjeta de débito'), ('99', '99 - Por definir')], help_text='Forma de pago según catálogo del SAT', max_length=2)),
                ('cliente', models.CharField(help_text='Nombre del cliente', max_length=200)),
                ('rfc_cliente', models.CharField(blank=True, help_text='RFC del cliente', max_length=13, null=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF del complemento', null=True, upload_to='complementos_pago/')),
                ('requiere_revision', models.BooleanField(default=False, help_text='Marca si el complemento requiere revisión manual')),
                ('motivo_revision', models.TextField(blank=True, help_text='Motivo por el que requiere revisión', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales', null=True)),
            ],
            options={
                'verbose_name': 'Complemento de Pago',
                'verbose_name_plural': 'Complementos de Pago',
                'ordering': ['-fecha_emision', '-folio_complemento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_factura_relacionada', models.CharField(help_text='UUID de la factura relacionada (para validación)', max_length=100)),
                ('num_parcialidad', models.IntegerField(default=1, help_text='Número de parcialidad de este pago (1, 2, 3...)')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, help_text='Saldo antes de este pago', max_digits=12)),
                ('importe_pagado', models.DecimalField(decimal_places=2, help_text='Monto pagado en esta parcialidad', max_digits=12)),
                ('saldo_insoluto', models.DecimalField(decimal_places=2, help_text='Saldo restante después de este pago', max_digits=12)),
                ('iva_desglosado', models.DecimalField(blank=True, decimal_places=2, help_text='IVA desglosado en el complemento', max_digits=10, null=True)),
                ('ieps_desglosado', models.DecimalField(blank=True, decimal_places=2, help_text='IEPS desglosado en el complemento', max_digits=10, null=True)),
                ('complemento', models.ForeignKey(help_text='Complemento de pago', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_relacionados', to='ventas.complementopago')),
                ('factura', models.ForeignKey(help_text='Factura que se está pagando', on_delete=django.db.models.deletion.CASCADE, related_name='complementos_relacionados', to='ventas.factura')),
                ('pago_factura', models.OneToOneField(blank=True, help_text='PagoFactura interno vinculado a este complemento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_relacionado', to='ventas.pagofactura')),
            ],
            options={
                'verbose_name': 'Documento Relacionado',
                'verbose_name_plural': 'Documentos Relacionados',
                'ordering': ['num_parcialidad'],
                'constraints': [models.UniqueConstraint(fields=('complemento', 'factura'), name='unique_complemento_factura')],
            },
        ),
    ]
