# Generated by Django 5.1.2 on 2026-01-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_complementopago_documentorelacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_vpg',
            field=models.BooleanField(default=False, help_text='Marca si es una Venta Público General (no tiene folio fiscal)'),
        ),
        migrations.AddField(
            model_name='factura',
            name='folio_vpg_anio',
            field=models.IntegerField(blank=True, help_text='Año del folio VPG (ej: 2025)', null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='folio_vpg_numero',
            field=models.IntegerField(blank=True, help_text='Número consecutivo del VPG en el año (ej: 1, 2, 3...)', null=True),
        ),
    ]
