# Generated by Django 5.1.2 on 2026-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_factura_es_vpg_factura_folio_vpg_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='folio_numero',
            field=models.IntegerField(blank=True, db_index=True, help_text='Número extraído del folio para ordenamiento', null=True),
        ),
    ]
