# Generated by Django 5.1.2 on 2026-01-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_factura_folio_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='folio_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
