# Generated by Django 5.1.2 on 2025-04-20 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_producto_proveedor'),
        ('inventario', '0007_productonoreconocido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraproducto',
            name='detectado_como',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compraproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
