# Generated by Django 5.1.2 on 2025-04-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_compraproducto_detectado_como_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='uuid',
            field=models.CharField(default='sin-uuid', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
