# Generated by Django 5.1.2 on 2025-11-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_compra_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_revision',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado_ok', 'Revisado OK'), ('revisado_con_cambios', 'Revisado con cambios')], default='pendiente', help_text='Estado de la revisión manual', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='requiere_revision_manual',
            field=models.BooleanField(default=False, help_text='Indica si la compra requiere revisión humana'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='motivo_revision',
            field=models.CharField(blank=True, help_text='Motivos por los que requiere revisión', max_length=255),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='requiere_revision_manual',
            field=models.BooleanField(default=False, help_text='Indica si esta línea requiere revisión'),
        ),
    ]
