# Generated by Django 5.1.2 on 2025-11-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_compra_estado_revision_and_more'),
        ('inventario', '0012_producto_costo_transporte'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compraproducto',
            constraint=models.UniqueConstraint(fields=('compra', 'producto'), name='unique_compra_producto'),
        ),
    ]
