# Generated by Django 5.1.2 on 2025-12-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compraproducto_unique_compra_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='costo_transporte_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de transporte por unidad/botella. Ej: $15.00 para Secretos de la Vid', max_digits=10),
        ),
    ]
