# Generated by Django 5.1.2 on 2025-12-23 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_proveedor_costo_transporte_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='transferencia', help_text='Método utilizado para el pago', max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Número de cheque, referencia de transferencia, etc.', max_length=100, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='compras.compra')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compras',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
